### ISSUE TITLE
Domoticz 2020.2 compatibility?

### ISSUE THREAD

**Issue by enesbcs** [dtlzp/Domoticz-Dingtian-Relay-Plugin#1]
Plugin do not work in Domoticz 2020.2

```
2020-10-10 17:44:42.408 Status: User: Admin initiated a switch command (12/ding - RELAY2/On)
2020-10-10 17:44:42.421 Error: (ding) 'onCommand' failed 'AttributeError':''NoneType' object has no attribute 'Send''.
2020-10-10 17:44:42.421 Error: (ding) ----> Line 185 in '/home/enes/domoticz/plugins/Domoticz-Dingtian-Relay-Plugin/plugin.py'
2020-10-10 17:44:42.421 Error: (ding) ----> Line 125 in '/home/enes/domoticz/plugins/Domoticz-Dingtian-Relay-Plugin/plugin.py' 
```

**Comment by enesbcs** [comment]
Never mind, after disabling debugging inside plugin settings, it works.
